### ISSUE TITLE
Default value for SEARCH_UI_JSTEMPLATE_RANGE does not exists.

### ISSUE THREAD

**Issue by jma** [inveniosoftware/invenio-search-ui#41] opened 2016-10-18 12:33 UTC
Hello,

using the default config, I got an error in the web debugger. It seems that templates defined by:
`SEARCH_UI_JSTEMPLATE_RANGE = 'templates/invenio_search_ui/range.html'`

does not exists.

**Comment by dinosk** [comment] 2017-11-21 13:38
I couldn't reproduce this.

**Comment by krzysztof** [comment] 2017-11-21 14:22
Looks like @diegodelemos already solved it in August: https://github.com/inveniosoftware/invenio-search-ui/commit/3b6c10f437cc240d21fcdbf201813363751b14ae#diff-9f15dc8ccde101566573b9fc9c32cba8R49

**Comment by diegodelemos** [comment] 2017-11-21 15:21
Closing as solved in https://github.com/inveniosoftware/invenio-search-ui/pull/50 (tested locally using example app)

**Closed by diegodelemos** 2017-11-21 15:21 UTC
Labels: Type: bug
